### ISSUE TITLE
URGENT: HelloWorldSample not getting detected in Android Auto

### ISSUE THREAD

**Issue by Android-AutoErrors** [android/car-samples#14]
Hi, 
I downloaded the HelloWorldSample from the repository and its not getting detected on the Android Auto App under generalised launcher. I changed the Developer settings of Android Auto as well. 
Although when I did the given changes in my android manifest file:-
**FROM:-**
```
<service android:name=".AndroidAuto.HelloWorldService" android:exported="true">
<intent-filter>
                <action android:name="androidx.car.app.CarAppService"/>
                <category android:name="androidx.car.app.category.NAVIGATION"/>
</intent-filter>
</service>
```

**TO:-**
```
<service android:name=".AndroidAuto.HelloWorldService" android:exported="true">
<intent-filter>
<action android:name="android.media.browse.MediaBrowserService" />
</intent-filter>
</service>
```

&

Automative app desc file code for Android auto from:-

```
<automotiveApp xmlns:tools="http://schemas.android.com/tools">
    <uses name="template" />
</automotiveApp>
```

to 
```
<automotiveApp xmlns:tools="http://schemas.android.com/tools">
    <uses name="media" />
</automotiveApp>
```

it was getting detected and was working fine.

Please guide us on how to get the App detected in Android Auto for Navigation as the same settings are working fine for Media app.

Other details you might find relevant:
Android Studio Version: 4.2.1
Android Auto is running on Device with Android 10
Google services version is: 4.3.8
Desktop head unit version is: 1.1
Build tool version is : 30.0.3
Min Sdk Version: 23
Target sdk version : 30

Thanks in advance.

**Comment by yjm607** [comment]
Following up in https://issuetracker.google.com/188705847
