### ISSUE TITLE
Google Automotive App Host Unavailable for Pixel 5

### ISSUE THREAD

**Issue by jdowfa** [android/car-samples#28]
Issue Description: Google Automotive App Host - This app is not available for any of your devices. This service seems to be a core requirement for running an Android Automotive application, yet isn't available for my Pixel 5. Is there a list of devices somewhere that are supported? Am I missing something? 

Replication:
1. Try to run the hello world automotive build using the DHU and Pixel 5
2. "System Requires Update" displays
3. Select "Update"
4. Redirect to "https://play.google.com/store/apps/details?id=com.google.android.apps.automotive.templates.host&hl=en_US&gl=US"
5. This app is not available for any of your devices

**Comment by vy12021** [comment]
The automotive app can not run on the phone side. You need to create an automotive emulated device with the automotive host app installed on it.
