### ISSUE TITLE
system requires update

### ISSUE THREAD

**Issue by jikun2008** [android/car-samples#29]
hello world run on automotive ematulor  it have info system requires update info

**Comment by ellisonchan** [comment]
Me too. 
Both on Volvo and polestar2 emulator.

**Comment by anilchahalaig** [comment]
Facing the same issue. After running the app it says, 

System requires update
CTA -> Check for Updates


And it was crashing on Check for Updates

**Comment by bsagmoe** [comment]
Running `adb shell am start https://play.google.com/store/apps/details?id=com.google.android.apps.automotive.templates.host` should take you to the Play Store page for the [Google Automotive App Host](https://play.google.com/store/apps/details?id=com.google.android.apps.automotive.templates.host) where you can install any updates available (which will fix this issue). Do note that you'll need to be logged into a Google account on the emulator to be able to see the page/download updates.
