### ISSUE TITLE
CURRENT_GEAR should be GEAR_SELECTION 

### ISSUE THREAD

**Issue by nikagl** [android/car-samples#3]
Correct me if I'm wrong, but CURRENT_GEAR should be GEAR_SELECTION here:

https://github.com/android/car-samples/blob/f2a7a8d404fc26f86b606e53f2b02fde55af5878/AutomotiveOS/CarGearViewerKotlin/automotive/src/main/java/com/example/cargearviewer/MainActivity.kt#L93

**Comment by Zhomart** [comment]
why do you think so?

**Comment by Zhomart** [comment]
According to [VehiclePropertyIds.java](https://cs.android.com/android/platform/superproject/+/master:packages/services/Car/car-lib/src/android/car/VehiclePropertyIds.java;l=281;drc=2f344bff1e8f5960ddb5b8e6876cbc2a45664833), both represent the current gear. As this is just a sample code, it shouldn't matter which one. (Please let me know if you disagree)

```
    /**
     * Currently selected gear
     *
     * This is the gear selected by the user.
     * Requires permission: {@link Car#PERMISSION_POWERTRAIN}.
     */
    @RequiresPermission(Car.PERMISSION_POWERTRAIN)
    public static final int GEAR_SELECTION = 289408000;
    /**
     * Current gear. In non-manual case, selected gear may not
     * match the current gear. For example, if the selected gear is GEAR_DRIVE,
     * the current gear will be one of GEAR_1, GEAR_2 etc, which reflects
     * the actual gear the transmission is currently running in.
     * Requires permission: {@link Car#PERMISSION_POWERTRAIN}.
     */
    @RequiresPermission(Car.PERMISSION_POWERTRAIN)
    public static final int CURRENT_GEAR = 289408001;
```

**Comment by nikagersonlohman** [comment]
Test it in the emulator. It's not ;)

**Comment by nikagersonlohman** [comment]
![image](https://user-images.githubusercontent.com/75429776/114475014-b3c21300-9bf7-11eb-9a4d-60bec996973b.png)

**Comment by nikagersonlohman** [comment]
And here's the code for the view (derived from your demo code :-) ):
```
    private var carPropertyCurrentGearListener = object : CarPropertyManager.CarPropertyEventCallback {
        override fun onChangeEvent(value: CarPropertyValue<Any>) {
            Log.d(TAG, "Received on changed car property event")
            // value.value type changes depending on the vehicle property.
            currentGearTextView.text = value.value.toString()
        }

        override fun onErrorEvent(propId: Int, zone: Int) {
            Log.w(TAG, "Received error car property event, propId=$propId, zone=$zone")
        }
    }

    private var carPropertyIgnitionStateListener = object : CarPropertyManager.CarPropertyEventCallback {
        override fun onChangeEvent(value: CarPropertyValue<Any>) {
            Log.d(TAG, "Received on changed car property event")
            // value.value type changes depending on the vehicle property.
            ignitionStateTextView.text = VEHICLE_IGNITION_STATES.getOrDefault(value.value as Int, "IGNITION_STATE_INVALID")
        }

        override fun onErrorEvent(propId: Int, zone: Int) {
            Log.w(TAG, "Received error car property event, propId=$propId, zone=$zone")
        }
```

**Comment by Zhomart** [comment]
you're right, it doesn't show GEAR_SELECTION. It shows CURRENT_GEAR, which can be changed in `Vhal properties` tab (next to the `Car Sensor Data` tab).

Search for `gear` and change the value of `current gear`, it will update the Gear Viewer app UI.

(looks like emulator should be updated, as CURRENT_GEAR should show the actual gear value)

**Comment by nikagersonlohman** [comment]
The  emulator doesn't allow me driving anyway, as soon as I start "driving" the screen shows a message I am not allowed to use my app while driving :)

**Comment by Zhomart** [comment]
https://github.com/android/car-samples/pull/11 this CL should fix your issue. Please read https://source.android.com/devices/automotive/driver_distraction/guidelines  to learn more about UX Restrictions
