### ISSUE TITLE
Sample Apps not showing in DHU

### ISSUE THREAD

**Issue by imagineDev** [android/car-samples#7]
The new sample apps like Showcase, etc are not showing in the DHU by default.
Even my own app used to work on DHU, but as soon as I migrate it to androidx, it does not show on the DHU anymore.

I am using the same HostValidator as shown in these sample apps. Kindly help

**Comment by croccio** [comment]
@imagineDev how do you resolve this issue? have u uploaded it to playstore? or do u can show it on androdi auto without uploading it on play store?

**Comment by imagineDev** [comment]
This was an strange issue. My phone used to work with DHU, and I was testing my app on it, but as soon as I migrated my code to AndroidX Car library, suddenly DHU stopped showing my app in the menu.

I tried to update/ reinstall the DHU, etc nothing worked.

Finally I uninstalled and then re-installed the Android Auto Client app, and it started to work again. 🤷🏻‍♂️
